### ISSUE TITLE
Redireccionamiento de puerto [Ruby on Rails + nginx]

### ISSUE THREAD

**Issue by dvogaz** [dfvasquez/aws-eb-multicontainer-docker#1]
Estoy desarrollando una app web con Ruby on Rails en AWS EC2 y me estaba costando muchísimo redireccionar el puerto desde el 3000 al 80 usando nginx, no encontraba cómo configurarlo bien. Había logrado dirigir solo la página principal y no la app completa. 
El archivo default.conf de este repositorio me solucionó el problema, gracias por compartirlo. Específicamente me faltaba la configuración de location
```
location / {
        proxy_pass http://IP:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
```

**Comment by dfvasquez** [comment]
Perfecto!! Me alegro mucho de que te haya sido útil la documentación 🤓
